server:
  port: 9080
spring:
  #\u6570\u636E\u5E93\u914D\u7F6E
  datasource:
    url: jdbc:mysql://49.235.85.17:3306/learning?rewriteBatchedStatements=true&useSSL=false&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&allowMultiQueries=true
    username: wuxjian
    password: wuxjian@J!31
  # thymeleaf \u6A21\u677F
  thymeleaf:
    cache: false # \u662F\u5426\u5F00\u542F\u7F13\u5B58\uFF0C\u5F00\u53D1\u4E2D\u8BBE\u7F6E\u6210false,\u4FBF\u4E8E\u66F4\u6539\u6587\u4EF6\u540E\uFF0C\u81EA\u52A8\u5237\u65B0
    check-template: true # \u68C0\u67E5\u6A21\u677F\u662F\u5426\u5B58\u5728
    enable-spring-el-compiler: false # \u662F\u5426spring el \u8868\u8FBE\u5F0F
    excluded-view-names:  # \u6307\u5B9A\u4E0D\u89E3\u6790\u7684\u89C6\u56FE\u540D\u4EE5\u9017\u53F7\u5206\u9694\uFF0C
    prefix: classpath:/templates/ # \u6A21\u677F\u6587\u4EF6\u8DEF\u5F84\u524D\u7F00
    suffix: .html # \u6587\u4EF6\u540E\u7F00
# mybatis \u914D\u7F6E
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
